version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: easy_interview
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '7777:5432'
  redis:
    image: 'redis:7.0.7-alpine'
    ports:
      - '6379:6379'
  pgadmin:
    container_name: pgadmin4_container_pc
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  # web:
  #   image: versevent/node-easy-interview
  #   build:
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
